# Generated by Django 5.1.7 on 2026-10-07 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


def deduplicate_authors(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Author = apps.get_model('books', 'Author')
    Book = apps.get_model('books', 'Book')
    authors_by_name = {}

    for author in Author.objects.using(db_alias).order_by('pk').iterator():
        authors_by_name.setdefault(author.name, []).append(author)

    for authors in authors_by_name.values():
        if len(authors) < 2:
            continue

        canonical = authors[0]
        biographies = list(dict.fromkeys(
            author.biography for author in authors if author.biography
        ))
        merged_biography = '\n\n'.join(biographies) or None
        if canonical.biography != merged_biography:
            canonical.biography = merged_biography
            canonical.save(using=db_alias, update_fields=['biography'])

        for duplicate in authors[1:]:
            Book.objects.using(db_alias).filter(author_id=duplicate.pk).update(
                author_id=canonical.pk
            )
            duplicate.delete(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_author_alter_book_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(deduplicate_authors),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('owner', 'title')},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['owner', 'is_read'], name='books_book_owner_i_a687b1_idx'),
        ),
    ]
